{"name": "test_get_dep", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 0", "trace": "self = <scripts.test_02_dep.TestDep object at 0x000002169A119B70>\n\n    @pytest.mark.run(order=2)\n    def test_get_dep(self):\n        print(\"222222222222222222222\")\n>       assert 1 == 0\nE       assert 1 == 0\n\nscripts\\test_02_dep.py:21: AssertionError"}, "start": 1704894472132, "stop": 1704894472132, "uuid": "0da24d80-d281-4674-a603-07a89be6d7ab", "historyId": "5fb787a19f5386780cbfd4cc66c18696", "testCaseId": "5fb787a19f5386780cbfd4cc66c18696", "fullName": "scripts.test_02_dep.TestDep#test_get_dep", "labels": [{"name": "tag", "value": "run(order=2)"}, {"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test_02_dep"}, {"name": "subSuite", "value": "TestDep"}, {"name": "host", "value": "WuMingming"}, {"name": "thread", "value": "26388-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test_02_dep"}]}